# Generated by Django 5.0.4 on 2024-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(default=1, verbose_name='Batafsil'),
            preserve_default=False,
        ),
    ]
